import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { BottomNavigation, BottomNavigationAction } from "@mui/material";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import "./globals.css";
import 'mapbox-gl/dist/mapbox-gl.css';
import RestoreIcon from '@mui/icons-material/Restore';
import FavoriteIcon from '@mui/icons-material/Favorite';
import ArchiveIcon from '@mui/icons-material/Archive';
import { Home, Search, Settings } from "@mui/icons-material";
import Paper from '@mui/material/Paper';
import { Box, Stack } from "@mui/material";

const inter = Inter({ subsets: ["latin"], });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        height: "100%"
      }}>
        <Stack sx={{
          height: "100%",
        }}>
          <Box sx={{
            height: "100%",
            maxHeight: "100vh",
            paddingBottom: "64px"
          }}>
            {children}
          </Box>
          <Box>
            <Paper sx={{ position: 'fixed', bottom: 0, left: 0, right: 0 }} elevation={3}>
              <BottomNavigation
                showLabels
              // value={value}
              // onChange={(event, newValue) => {
              //   setValue(newValue);
              // }}
              >
                <BottomNavigationAction label="Início" icon={<Home />} />
                <BottomNavigationAction label="Histórico" icon={<Search />} />
                <BottomNavigationAction label="Ajustes" icon={<Settings />} />
              </BottomNavigation>
            </Paper>
          </Box>
        </Stack>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        />
      </body>

    </html>
  );
}
